# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9e177678af0db057b5a01a6e64e69d376d7f96640865997741f74330dd46642cc255544cc019dfd08f14019792f38f364343d4a2ae726b38c2fa8e302e38eca

test:
  secret_key_base: a25cea5157345a0ace2ab3c11b197eb49498aec89ebcd7f5c8d906d11256414facf7ac6f37303019e8481a8969bfc50cbc131eede828711f91301b07e941ba0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
